config/routes.rb
Rails.application.routes.draw do
  resources :trips

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#dashboard'
  resources :requests

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :host, class_name: 'User'
end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  has_many :requests
  has_many :trips
  has_many :hosts, through: :requests

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.access_token = auth.credentials.token
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.location = auth.extra.raw_info.location.name unless auth.extra.raw_info.location.nil?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    trips_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @users = User.all

    if current_user
      @user_requests = current_user.requests.where(user_id: current_user.id)
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def create
    @request = current_user.requests.build(host_id: params[:host_id])
    @request.status = 'Pending host acceptance'
    if @request.save
      flash[:notice] = 'Request sent.'
      redirect_to root_url
    else
      flash[:notice] = 'Request failed to send.'
      redirect_to root_url
    end
  end

  def destroy
    @request = current_user.requests.find(params[:id])
    @request.destroy
    flash[:notice] = 'Request deleted'
    redirect_to root_path
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.where(user_id: current_user.id)
    require 'byebug'; byebug
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def generate_requests(destination)
      graph = Koala::Facebook::API.new(current_user.access_token)
      location = graph.get_object('me')['location']

      friends = @graph.get_connections('me', 'friends')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:destination, :start_date, :end_date, :user_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Go</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>
    var _roost = _roost || [];
    _roost.push(['appkey','7bf8560ecee0487cbf9b1bb6c70136ad']);

    !function(d,s,id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if(!d.getElementById(id)){
        js=d.createElement(s); js.id=id;
        js.src='//cdn.goroost.com/js/roost.js';
        fjs.parentNode.insertBefore(js,fjs);
      }
    }(document, 'script', 'roost-js');
  </script>
</head>
<body>
<p class='notice'><%= notice %></p>
<p class='alert'><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/pages/dashboard.html.erb
<% if current_user.nil? %>
  <div class="background"><div class="shade"></div></div>
  <div class="container landing">
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 132.3 56.4" enable background="new 0 0 132.3 56.4" xml:space="preserve">
      <g>
        <path fill="#4FA6F2" d="M69.1,0.8c-1.5-0.8-3.1-1-4.5-0.7c-1.5,0.4-3.1,1.2-4.7,2.4c-1.6,1.2-3.2,2.9-4.9,4.9c-1.7,2-3.4,4.3-5.1,6.7l-0.2,0.4l-0.4,0c-3.4,0.4-7.1,0.5-11.2,0.3c-4.1-0.2-8.5-1-13.2-2.2c-0.1,0-0.2-0.1-0.4,0.1c-0.1,0.1-0.3,0.3-0.2,0.9c0,0.5,0.3,1.1,0.8,1.8c0.5,0.7,1.4,1.4,2.7,2.1c1.4,0.7,3.2,1.2,5.6,1.7c2.3,0.5,5.3,0.6,8.9,0.6h3.6l-1,1.7c-1.5,2.3-3.1,4.6-4.6,6.8c-1.6,2.2-3.2,4.4-4.9,6.4l-0.5,0.5L34.2,35c-2.2-0.8-4.5-1.5-6.8-2c-2.3-0.5-4.7-0.9-7-1c-2.3-0.1-4.6,0-6.9,0.3c-2.2,0.3-4.4,1.1-6.5,2.1c-2.2,1.1-3.8,2.3-5,3.6c-1.1,1.3-1.8,2.6-2,4c-0.2,1.3-0.1,2.6,0.4,3.8C1,47.2,1.8,48.3,3,49.3c1.2,1,2.7,1.8,4.5,2.4c1.8,0.6,3.9,0.8,6.1,0.7c4.3-0.2,8.2-1.2,11.8-2.9c3.6-1.7,7-4,10-6.7l0.5-0.4l0.6,0.3c4.9,2.4,8.8,4.8,11.8,7.1c2.9,2.3,5.2,4.4,6.6,6.1c0.4,0.5,0.6,0.6,0.8,0.6c0.3-0.1,0.6-0.4,0.9-0.9c0.3-0.6,0.5-1.4,0.7-2.4c0.1-1,0-2.1-0.3-3.3c-0.3-1.2-0.9-2.3-1.7-3.4c-0.8-1.1-1.9-2.1-3.3-2.9c-1.3-0.8-2.9-1.6-4.6-2.5c-1.7-0.9-3.5-1.8-5.5-2.8l-1.2-0.6l0.9-1c2.5-2.9,4.8-6,6.9-9c2.1-3.1,4-6.1,5.7-9l0.2-0.3l0.4-0.1c3.5-1.1,6.5-2.5,9.1-4.2c2.5-1.7,4.5-3.5,5.8-5.3c1.2-1.7,1.9-3.3,1.8-4.8C71.3,2.6,70.6,1.6,69.1,0.8z M29.5,41c-2.4,2.2-4.9,3.9-7.5,5.2c-2.6,1.3-5.4,2-8.3,2c-2.4,0-4.2-0.4-5.6-1.2c-1.4-0.9-2.2-2-2.4-3.2c-0.2-1.3,0.2-2.5,1.1-3.8c0.9-1.2,2.3-2.1,4.1-2.7c1.8-0.6,4-0.9,6.6-0.8c2.6,0.1,5.6,0.7,9,1.9c1,0.4,1.8,0.7,2.6,1l1.6,0.6L29.5,41z M67.4,7.6c-0.7,0.7-1.6,1.5-2.8,2.2c-1.2,0.7-2.7,1.4-4.3,2.1L57.4,13l1.6-2.6c1.5-2.4,2.8-4.4,4-5.7C64.3,3,65.8,2.5,67.1,3c1.4,0.6,1.5,1.6,1.5,2.2C68.5,5.9,68.1,6.7,67.4,7.6z"/>
        <path fill="#4FA6F2" d="M59.7,23.2c1.2,0,2.2,0.2,3,0.7c0.8,0.5,1.5,1.1,1.9,1.9c0.4,0.8,0.7,1.7,0.7,2.8c0,1.1-0.1,2.2-0.5,3.5c0.3,0.2,0.7,0.4,1.2,0.5c0.5,0.1,0.9,0.2,1.4,0.1c0.5,0,0.9-0.2,1.4-0.4c0.4-0.2,0.8-0.5,1.1-1c0.3-0.5,0.7-0.9,1.1-1c0.4-0.2,0.7-0.2,0.9,0c0.2,0.1,0.4,0.4,0.4,0.8c0,0.4-0.2,0.8-0.6,1.3c-0.6,0.8-1.2,1.4-1.9,1.9c-0.7,0.4-1.4,0.7-2.1,0.9c-0.7,0.2-1.4,0.2-2.1,0.1c-0.7-0.1-1.3-0.3-1.8-0.6c-0.5,1-1.2,1.9-1.9,2.8c-0.7,0.8-1.5,1.6-2.4,2.2c-0.9,0.6-1.8,1.1-2.8,1.4c-1,0.3-2,0.5-3,0.5c-1.2,0-2.2-0.2-3-0.7c-0.8-0.5-1.5-1.1-1.9-2c-0.4-0.8-0.7-1.8-0.7-2.9c0-1.1,0.2-2.3,0.6-3.6c0.4-1.3,1-2.4,1.8-3.6c0.8-1.1,1.6-2.1,2.6-2.9c1-0.8,2.1-1.5,3.2-2C57.2,23.4,58.4,23.2,59.7,23.2z M56.1,36.4c1.1,0,2.2-0.4,3.1-1.1c1-0.7,1.7-1.7,2.3-2.8c-0.5-0.6-0.8-1.2-0.9-1.7c-0.2-0.6-0.3-1.1-0.3-1.6c0-0.5,0-1,0.1-1.4c0.1-0.4,0.2-0.8,0.4-1.2c-0.2-0.1-0.3-0.1-0.6-0.1c-0.2,0-0.4,0-0.7,0c-1.4,0-2.5,0.5-3.6,1.5s-1.8,2.1-2.3,3.5c-0.5,1.4-0.5,2.6-0.1,3.6C53.9,35.9,54.8,36.4,56.1,36.4z"/>
        <path fill="#4FA6F2" d="M94.9,32.3c-0.7,1.2-1.6,2.3-2.6,3.4c-1,1.1-2.1,2.1-3.2,2.9c-1.1,0.9-2.3,1.5-3.5,2c-1.2,0.5-2.3,0.8-3.3,0.8c-1.1,0-2-0.4-2.6-1.2c-0.6-0.8-1-1.8-1-2.9c-0.4,0.5-0.8,0.9-1.2,1.4c-0.5,0.5-1,0.9-1.5,1.3c-0.6,0.4-1.2,0.8-1.9,1c-0.7,0.3-1.5,0.4-2.3,0.4c-1.3,0-2.3-0.3-3.1-1c-0.8-0.7-1.4-1.6-1.7-2.7c-0.3-1.1-0.3-2.4,0-3.8c0.3-1.4,1-2.9,2.1-4.3c0.9-1.3,2-2.3,3.1-3.1c1.1-0.8,2.3-1.5,3.5-1.9c1.2-0.4,2.3-0.6,3.4-0.5c1.1,0.1,2.1,0.4,3,0.9c0.3-0.8,0.7-1.6,1.1-2.5c0.4-0.9,0.8-1.8,1.2-2.6c0.4-0.8,0.8-1.6,1.1-2.3c0.3-0.7,0.6-1.3,0.8-1.8c0.3-0.7,0.6-1.3,0.8-1.7c0.2-0.4,0.4-0.8,0.7-1.1c0.2-0.3,0.5-0.5,0.8-0.7c0.3-0.2,0.8-0.3,1.4-0.5c0.6-0.2,1.2-0.3,1.7-0.5c0.6-0.1,1-0.2,1.4-0.2c0.4,0,0.7,0.1,0.8,0.4c0.1,0.2,0.1,0.7-0.2,1.3c-0.2,0.4-0.5,1-0.9,1.9c-0.4,0.8-0.8,1.8-1.3,2.9c-0.5,1.1-1,2.2-1.6,3.4c-0.6,1.2-1.1,2.4-1.6,3.5c-0.5,1.1-1,2.1-1.4,3.1c-0.4,0.9-0.8,1.7-1,2.2c-0.4,0.8-0.7,1.6-1,2.4s-0.5,1.6-0.6,2.3c-0.1,0.7,0,1.3,0.2,1.7c0.2,0.4,0.7,0.7,1.4,0.7c1.4,0,2.8-0.5,4.1-1.5c1.3-1,2.4-2.3,3.3-3.9c0.3-0.5,0.7-0.9,1-1c0.3-0.2,0.6-0.2,0.9-0.1c0.2,0.1,0.4,0.4,0.4,0.8C95.4,31.3,95.2,31.8,94.9,32.3z M73.5,36.8c1.4,0,2.6-0.8,3.6-2.3c1.1-1.5,2.2-3.6,3.3-6.3L80,28c-0.5-0.2-1.2-0.2-1.9-0.1c-0.7,0.1-1.4,0.4-2.1,0.8c-0.7,0.4-1.4,0.9-2.1,1.5c-0.7,0.6-1.3,1.3-1.7,2.2c-0.3,0.5-0.5,1.1-0.7,1.6c-0.1,0.5-0.1,1,0,1.5c0.1,0.4,0.3,0.8,0.7,1C72.5,36.7,72.9,36.8,73.5,36.8z"/>
        <path fill="#4FA6F2" d="M92.3,29.6c1-1.3,2-2.4,3.2-3.2c1.2-0.9,2.4-1.5,3.6-1.9c1.2-0.4,2.4-0.5,3.5-0.4c1.1,0.1,2.1,0.5,3,1.2c0.2-0.4,0.4-0.6,0.6-0.9c0.2-0.2,0.4-0.4,0.7-0.5c0.2-0.1,0.5-0.2,0.8-0.3c0.3-0.1,0.7-0.2,1.2-0.2c0.5-0.1,1-0.1,1.5-0.1c0.5,0,0.8,0,1.1,0.1c0.3,0.1,0.4,0.3,0.4,0.6c0,0.3-0.1,0.8-0.4,1.3c-0.3,0.6-0.7,1.3-1.1,2c-0.4,0.7-0.8,1.4-1.2,2.1c-0.4,0.7-0.8,1.4-1.2,2c-0.4,0.6-0.7,1.2-1,1.7c-0.5,0.8-0.9,1.6-1.4,2.5c-0.4,0.9-0.9,1.8-1.3,2.7c1.7-0.7,3.4-1.6,5-2.7c1.6-1.1,3.1-2.5,4.4-4.3c0.4-0.4,0.7-0.7,1.1-0.9c0.4-0.2,0.7-0.2,0.9-0.1c0.2,0.1,0.4,0.3,0.4,0.7c0,0.3-0.2,0.8-0.6,1.4c-0.8,1.3-1.7,2.4-2.7,3.3c-1,1-2.1,1.8-3.2,2.5c-1.1,0.7-2.3,1.4-3.5,1.9c-1.2,0.5-2.4,1-3.6,1.4c-0.9,1.6-2,3.2-3.1,4.5c-1.2,1.4-2.7,2.4-4.5,3c-1.5,0.5-2.9,0.8-4.2,0.7c-1.2-0.1-2.3-0.3-3.1-0.8c-0.8-0.5-1.5-1.1-1.9-1.8c-0.4-0.8-0.6-1.6-0.6-2.4c0-0.8,0.3-1.7,0.8-2.5c0.5-0.8,1.3-1.5,2.4-2.1c0.4-0.2,0.7-0.4,1.1-0.5c0.4-0.1,0.8-0.3,1.2-0.5c-0.7-1.2-1-2.6-0.8-4.3C90.3,33.1,91,31.4,92.3,29.6z M90.9,45.9c0.9,0,1.9-0.4,3.1-1.1c1.2-0.7,2.4-1.9,3.7-3.7c-0.9-0.2-1.9-0.3-2.9-0.3c-1,0-1.9,0.2-2.8,0.5c-1,0.4-1.8,0.8-2.3,1.3c-0.5,0.5-0.8,1-0.9,1.5c-0.1,0.5,0.1,0.9,0.4,1.3C89.6,45.7,90.2,45.9,90.9,45.9z M96.9,36.8c1.4,0,2.6-0.8,3.6-2.3c1.1-1.5,2.2-3.6,3.3-6.3l-0.4-0.2c-0.5-0.2-1.2-0.2-1.9-0.1c-0.7,0.1-1.4,0.4-2.2,0.8c-0.7,0.4-1.4,0.9-2.1,1.5c-0.7,0.6-1.3,1.3-1.7,2.2c-0.3,0.5-0.5,1.1-0.7,1.6c-0.1,0.5-0.1,1,0,1.5c0.1,0.4,0.3,0.8,0.7,1C95.8,36.7,96.3,36.8,96.9,36.8z"/>
        <path fill="#4FA6F2" d="M124.1,31.5c-1,0.9-2.3,1.7-3.8,2.3c-1.5,0.6-2.9,1.1-4.4,1.3c0.2,0.7,0.5,1.3,1,1.6c0.5,0.4,1,0.6,1.6,0.7c0.8,0.2,1.8,0.1,2.8-0.2c1-0.3,2.1-0.7,3.1-1.3c1-0.6,2-1.3,3-2.1c1-0.8,1.8-1.7,2.5-2.7c0.4-0.5,0.8-0.8,1.1-1c0.4-0.2,0.7-0.2,0.9,0c0.2,0.1,0.3,0.4,0.3,0.7c0,0.4-0.2,0.8-0.5,1.3c-1,1.4-2,2.6-3.2,3.8c-1.2,1.1-2.4,2.1-3.6,2.9c-1.3,0.8-2.6,1.4-3.9,1.8c-1.3,0.4-2.7,0.7-3.9,0.7c-1.5,0-2.7-0.3-3.8-0.9c-1-0.6-1.8-1.4-2.3-2.4c-0.5-1-0.7-2.2-0.6-3.6c0.1-1.4,0.6-2.9,1.4-4.4c0.5-1.1,1.3-2.2,2.1-3.2c0.9-1,1.8-1.9,2.9-2.5c1-0.7,2.2-1.1,3.3-1.4c1.2-0.2,2.3-0.1,3.5,0.4c0.9,0.4,1.5,0.9,2,1.5c0.5,0.6,0.7,1.3,0.7,2c0,0.7-0.1,1.5-0.5,2.3C125.5,30.1,124.9,30.8,124.1,31.5z M116.2,32.3c1.1-0.2,2.2-0.5,3.3-1c1.1-0.5,2.1-1.3,3-2.4c0.6-0.8,0.7-1.4,0.5-1.9c-0.3-0.5-0.8-0.7-1.5-0.6c-0.7,0.1-1.5,0.5-2.4,1.3c-0.9,0.8-1.8,2-2.5,3.7L116.2,32.3z"/>
      </g>
    </svg>
    <h2 class="head">Stay with the people you know.</h2>
    <a class="facebook" href="<%= user_omniauth_authorize_path(:facebook) %>"><div></div></a>
  </div>
<% else %>
  <%= link_to 'Create Trip', new_trip_path %>

  <h2>Users</h2>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= user.email %>
        <%= link_to 'Send Request', requests_path(host_id: user), method: :post %>
      </li>
    <% end %>
  </ul>

  <h2>Requests as user</h2>
  <% @user_requests.each do |request| %>
    <%= request.user_id %>
    <%= request.host_id %>
    <%= request.status %>
    <%= link_to 'destroy', request, method: :delete %>
  <% end %>

  <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/new.html.erb
<%= render 'form' %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>